services:
  sql2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Soy_Feliz_1234"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sql2022-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -Q \"SELECT 1\" >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  sql2022-data:
    driver: local
